// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsiQ9m0k9dRT0T0M7-eQDzUsHM0e26kv8',
    appId: '1:983604255533:web:57d00e04f2161c011bd1a4',
    messagingSenderId: '983604255533',
    projectId: 'do-it-now-a5725',
    authDomain: 'do-it-now-a5725.firebaseapp.com',
    storageBucket: 'do-it-now-a5725.appspot.com',
    measurementId: 'G-TWJVSJ3CE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_EGfJh6EWwcDyXC8RdCiVaBPlgnhfvp0',
    appId: '1:983604255533:android:8b6c7cb9545e14c11bd1a4',
    messagingSenderId: '983604255533',
    projectId: 'do-it-now-a5725',
    storageBucket: 'do-it-now-a5725.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSlY0FETkv68rvQssH2KU9Bc2M2nW70io',
    appId: '1:983604255533:ios:3e237e104f1897ff1bd1a4',
    messagingSenderId: '983604255533',
    projectId: 'do-it-now-a5725',
    storageBucket: 'do-it-now-a5725.appspot.com',
    iosClientId: '983604255533-9mb9t5omfqa5n72g25r2pg0tlj832ega.apps.googleusercontent.com',
    iosBundleId: 'com.example.din.RunnerTests',
  );
}
